### ISSUE TITLE
Emoji marks are not honoured.

### ISSUE THREAD

**Issue by drahnr** [bminixhofer/srx#5]
When using `U+203C`, `U+FE0F` :bangbang: or :exclamation: `U+2757` and others, sentence split does not work as anticipated.

**Comment by bminixhofer** [comment]
Are there any rules for emojis in the SRX file you're using which you would expect to match? 

If not, this isn't a problem with this crate and you'd have to take this up upstream with LanguageTool or add them yourself (assuming you are using LanguageTool's `segment.srx`).
