### ISSUE TITLE
error[E0599]

### ISSUE THREAD

**Issue by shinx2000** [bminixhofer/srx#8]
error[E0599]: no function or associated item named `from_str` found for struct `SRX` in the current scope
 --> segment/src/main.rs:9:20
  |
9 |     let srx = SRX::from_str(&fs::read_to_string("data/segment.srx").unwrap())?;
  |                    ^^^^^^^^ function or associated item not found in `SRX`

**Comment by ZJaume** [comment]
You need to enable the feature on your `Cargo.toml` with
```toml
srx = { version = "0.1", features = ["from_xml"] }
```
insead of
```
srx = { version = "0.1" }
```

If you are compiling the srx module directly instead of adding as a dependency, you need to run `cargo build --all-features`.

**Comment by bminixhofer** [comment]
Hi, sorry, I missed this issue earlier. Thanks @ZJaume for chiming in. Closing this as solved.
